# .github/workflows/test_action.yml
name: Validate trained model

on:
  workflow_run:
    workflows: ["Train model with Dagger"]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: ./model

      - name: Run model validator
        uses: lasselundstenjensen/itu-sdse-project-model-validator@v1
        with:
          model-path: "./model"
